"use client";
import Image from "next/image";
import Link from "next/link";
import {useState} from "react";
import {Icon,type IconName} from "../../_components/icons";
const gallery=[{src:"/images/products/camisa-termica-preta.png",alt:"Blusa térmica masculina Info Trilhas preta"},{src:"/images/products/segunda-pele-uv.png",alt:"Detalhe frontal do tecido técnico"},{src:"/images/products/calca-termica.png",alt:"Composição da linha para baixas temperaturas"}];
const tech:{title:string;text:string;icon:IconName}[]=[{title:"Proteção UV 50+",text:"Barreira para exposição solar durante atividades externas.",icon:"sun"},{title:"Conforto térmico",text:"Ajuda a equilibrar a temperatura corporal.",icon:"temperature"},{title:"Respirabilidade",text:"Favorece a troca de calor durante o movimento.",icon:"wind"},{title:"Secagem rápida",text:"Tecnologia que dispersa a umidade.",icon:"spark"},{title:"Fabricação própria",text:"Qualidade controlada em cada etapa.",icon:"shield"}];
export function ProductExperience(){const[image,setImage]=useState(0);const[color,setColor]=useState("Preto");const[size,setSize]=useState("M");const[guide,setGuide]=useState(false);const message=`Olá! Tenho interesse na Blusa Térmica Masculina Info Trilhas.\n\nCor: ${color}\nTamanho: ${size}\nQuantidade: 1\n\nGostaria de mais informações.`;return <main className="product-page"><div className="container-shell product-breadcrumb"><Link href="/">← Voltar para a loja</Link><span>Produto demonstrativo</span></div>
<section className="container-shell product-hero"><div className="product-gallery"><div className="product-main-image"><span className="uv-seal">FEITO<br/>NO BRASIL</span><Image src={gallery[image].src} alt={gallery[image].alt} fill priority sizes="(max-width: 900px) 94vw, 52vw"/></div><div className="product-thumbs">{gallery.map((item,index)=><button type="button" className={image===index?"active":""} onClick={()=>setImage(index)} key={item.src} aria-label={`Ver imagem ${index+1}`}><Image src={item.src} alt="" fill sizes="90px"/></button>)}</div></div>
<div className="product-buybox"><p className="product-kicker">Linha Block · Frio intermediário</p><h1>Blusa Térmica<br/>Masculina</h1><div className="product-rating"><span>★★★★★</span> <strong>4,9</strong> <small>(128 avaliações)</small></div><p className="product-positioning">Proteção térmica, respirabilidade e liberdade de movimento para motociclistas e aventuras em dias frios.</p><div className="product-availability ready"><i/>Pronta entrega <small>Envio disponível</small></div><div className="product-price"><strong>R$ 129,90</strong><span><b>R$ 116,91 no PIX</b> · 6x de R$ 21,65</span></div>
<div className="variation"><div><strong>Cor</strong><span>{color}</span></div><div className="choice-row">{["Preto","Azul","Branco"].map(item=><button type="button" onClick={()=>setColor(item)} className={color===item?"selected":""} key={item}><i className={`swatch ${item.toLowerCase()}`}/>{item}</button>)}</div></div><div className="variation"><div><strong>Tamanho</strong><button className="guide-link" type="button" onClick={()=>setGuide(true)}>Guia de medidas</button></div><div className="choice-row sizes">{["P","M","G","GG"].map(item=><button type="button" disabled={item==="GG"} title={item==="GG"?"Indisponível":undefined} onClick={()=>setSize(item)} className={size===item?"selected":""} key={item}>{item}</button>)}</div><small className="unavailable-note">GG disponível sob demanda nesta demonstração</small></div>
<div className="purchase-actions"><button type="button" className="buy secondary">Adicionar ao carrinho</button><button type="button" className="buy primary">Comprar agora</button><a className="buy whatsapp" href={`https://wa.me/5561982820643?text=${encodeURIComponent(message)}`} target="_blank" rel="noreferrer"><Icon name="message" size={18}/> Comprar pelo WhatsApp</a></div><div className="buy-trust"><span><Icon name="lock" size={17}/> Compra segura</span><span><Icon name="truck" size={18}/> Envio para todo o Brasil</span></div></div></section>
<section className="product-tech"><div className="container-shell"><p className="eyebrow light"><span/>Tecnologia Info Trilhas</p><h2>Não é apenas roupa.<br/>É proteção técnica.</h2><div className="product-tech-grid">{tech.map(item=><article key={item.title}><Icon name={item.icon} size={26}/><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div></section>
<section className="container-shell social-proof"><div className="product-section-heading"><p className="eyebrow"><span/>Experiência comprovada</p><h2>Avaliações dos clientes</h2><span>Dados demonstrativos</span></div><div className="review-grid">{[{name:"Mariana Alves",text:"Excelente acabamento e muito confortável na estrada.",img:"/images/products/segunda-pele-uv.png"},{name:"Rafael Costa",text:"Protege bem do frio e mantém liberdade de movimento.",img:"/images/products/camisa-termica-preta.png"}].map(review=><article key={review.name}><div className="review-photo"><Image src={review.img} alt="Foto ilustrativa da avaliação" fill sizes="70px"/></div><div><span className="stars">★★★★★</span><h3>{review.name}</h3><small>✓ Compra verificada</small><p>“{review.text}”</p></div></article>)}</div><div className="questions"><div><p className="eyebrow"><span/>Atendimento especializado</p><h2>Perguntas sobre o produto</h2></div><article><strong>Essa blusa térmica pode ser usada para motociclismo?</strong><p><b>Resposta Info Trilhas:</b> Sim. O tecido foi desenvolvido para oferecer conforto térmico, proteção e mobilidade durante atividades externas e viagens de moto.</p></article></div></section>
{guide&&<div className="modal-backdrop" role="presentation" onMouseDown={()=>setGuide(false)}><div className="size-modal" role="dialog" aria-modal="true" aria-labelledby="size-title" onMouseDown={event=>event.stopPropagation()}><button type="button" className="modal-close" onClick={()=>setGuide(false)} aria-label="Fechar">×</button><p className="eyebrow"><span/>Encontre seu ajuste</p><h2 id="size-title">Guia de medidas</h2><p>Medidas ilustrativas em centímetros.</p><div className="size-table"><div><b>Tamanho</b><b>Tórax</b><b>Comprimento</b></div>{[["P","88–94","66"],["M","95–101","68"],["G","102–108","70"],["GG","109–116","72"]].map(row=><div key={row[0]}>{row.map(cell=><span key={cell}>{cell}</span>)}</div>)}</div></div></div>}</main>}
