import Image from "next/image";
import Link from "next/link";
import { Footer } from "./_components/footer";
import { Header } from "./_components/header";
import { Icon, type IconName } from "./_components/icons";

const adventures: { name:string; eyebrow:string; icon:IconName; image:string; href:string }[] = [
  {name:"Motociclismo",eyebrow:"Proteção para a estrada",icon:"helmet",image:"/images/categories/motociclismo-card.png",href:"#linhas"},{name:"Ciclismo",eyebrow:"Conforto em movimento",icon:"bike",image:"/images/categories/ciclismo-card.png",href:"#linhas"},{name:"Corrida",eyebrow:"Leveza em cada passo",icon:"activity",image:"/images/categories/corrida-card.png",href:"#linhas"},{name:"Baixas temperaturas",eyebrow:"Pronto para o frio",icon:"temperature",image:"/images/categories/baixas-temperaturas-card.png",href:"#linhas"},{name:"Proteção UV",eyebrow:"Defesa contra o sol",icon:"sun",image:"/images/categories/protecao-uv-card.png",href:"#linhas"},{name:"Atacado",eyebrow:"Direto de quem fabrica",icon:"spark",image:"/images/categories/atacado-card.png",href:"#atacado"},
];
const products = [
  {name:"Blusa Térmica Masculina",image:"/images/products/camisa-termica-preta.png",badge:"Destaque",price:"R$ 129,90",installments:"3x de R$ 43,30",availability:"Pronta entrega",tone:"ready"},
  {name:"Segunda Pele UV 50+",image:"/images/products/segunda-pele-uv.png",badge:"Thermo Sun",price:"R$ 119,90",installments:"3x de R$ 39,97",availability:"Pronta entrega",tone:"ready"},
  {name:"Pernito Thermo Sun",image:"/images/products/pernito-thermo-sun.png",badge:"UV 50+",price:"R$ 79,90",installments:"2x de R$ 39,95",availability:"Produção sob demanda",tone:"demand"},
  {name:"Manguito UV 50+",image:"/images/products/manguito-uv.png",badge:"UV 50+",price:"R$ 59,90",installments:"2x de R$ 29,95",availability:"Pronta entrega",tone:"ready"},
  {name:"Calça Térmica",image:"/images/products/calca-termica.png",badge:"Comfort Extremo",price:"R$ 139,90",installments:"3x de R$ 46,63",availability:"Produção sob demanda",tone:"demand"},
  {name:"Balaclava Térmica",image:"/images/products/balaclava.png",badge:"Proteção",price:"R$ 49,90",installments:"2x de R$ 24,95",availability:"Encomenda especial",tone:"special"},
];
const technology: {title:string;text:string;icon:IconName}[] = [{title:"Proteção UV 50+",text:"Barreira para exposição prolongada ao sol.",icon:"sun"},{title:"Conforto térmico",text:"Equilíbrio de temperatura em diferentes condições.",icon:"temperature"},{title:"Respirabilidade",text:"Tecido inteligente que favorece a troca de calor.",icon:"wind"},{title:"Fabricação própria",text:"Controle de qualidade em cada etapa da produção.",icon:"shield"}];
const lines = [{kicker:"Linha 01 · Sol e meia-estação",name:"Thermo Sun",text:"Proteção UV 50+ e conforto térmico para atividades sob o sol.",detail:"Preto · Branco · Verde oliva · Azul-marinho",image:"/images/products/pernito-thermo-sun.png"},{kicker:"Linha 02 · Frio intermediário",name:"Block",text:"Proteção equilibrada contra vento e temperaturas amenas, sem limitar o movimento.",detail:"Conforto para estrada e rotina outdoor",image:"/images/products/camisa-termica-preta.png"},{kicker:"Linha 03 · Baixas temperaturas",name:"Comfort Extremo",text:"Isolamento e toque confortável para aventuras em condições de frio intenso.",detail:"Camadas técnicas para máxima proteção",image:"/images/products/calca-termica.png"}];
const benefits: {title:string;text:string;icon:IconName}[] = [{title:"Compra segura",text:"Seus dados sempre protegidos",icon:"lock"},{title:"Envio pelos Correios",text:"Segundas, quartas e sextas",icon:"truck"},{title:"Fabricação própria",text:"Qualidade controlada por nós",icon:"spark"},{title:"Pós-venda",text:"Atendimento que acompanha você",icon:"message"}];

export default function Home(){return <><Header/><main className="storefront">
<section className="hero" aria-labelledby="hero-title"><div className="hero-grid container-shell"><div className="hero-copy"><p className="eyebrow light"><span/>Vestuário técnico brasileiro</p><h1 id="hero-title">Por onde for, conforto e proteção é nosso compromisso com você.</h1><p className="hero-subtitle">Blusas térmicas e roupas de proteção desenvolvidas para a estrada, o frio e cada nova aventura.</p><div className="hero-actions"><a href="#mais-vendidos" className="button button-gold">Conheça a blusa térmica <Icon name="arrow" size={18}/></a><a href="#tecnologia" className="button button-outline">Nossa tecnologia</a></div><div className="hero-proof"><span><strong>Fabricação própria</strong>qualidade controlada</span><span><strong>Envios programados</strong>segundas, quartas e sextas</span><span><strong>Proteção e conforto</strong>vestuário técnico brasileiro</span></div></div><div className="hero-visual"><div className="hero-image-frame"><Image src="/images/products/camisa-termica-preta-cutout.png" alt="Blusa térmica masculina preta Info Trilhas" fill priority sizes="(max-width: 767px) 100vw, 46vw" className="hero-image"/></div><div className="hero-product-info"><small>Linha Block · Frio intermediário</small><strong>Blusa térmica masculina</strong><span>Pronta entrega · fabricação própria</span></div></div><div className="hero-benefits"><span><Icon name="sun" size={22}/><small>Proteção solar</small><strong>UV 50+</strong></span><span><Icon name="temperature" size={22}/><small>Conforto</small><strong>Térmico</strong></span><span><Icon name="wind" size={22}/><small>Respirável</small><strong>e leve</strong></span><span><Icon name="spark" size={22}/><small>Secagem</small><strong>rápida</strong></span></div></div></section>
<section className="section adventures" aria-labelledby="adventures-title"><div className="container-shell"><div className="section-heading"><div><p className="eyebrow"><span/>Proteção para cada caminho</p><h2 id="adventures-title">Escolha sua aventura</h2></div><p>Encontre vestuário técnico pensado para seu ritmo, sua atividade e o clima que você vai enfrentar.</p></div><div className="adventure-grid">{adventures.map(item=><a className="adventure-card" href={item.href} key={item.name}><Image src={item.image} alt="" fill sizes="(max-width: 767px) 100vw, 20vw"/><Icon name={item.icon} size={34}/><div><span>{item.eyebrow}</span><h3>{item.name}</h3></div><Icon name="arrow" size={18}/></a>)}</div></div></section>
<section className="section products-section" id="mais-vendidos" aria-labelledby="products-title"><div className="container-shell"><div className="section-heading products-heading"><div><p className="eyebrow"><span/>Conforto que protege</p><h2 id="products-title">Vestuário técnico em destaque</h2></div><p>Da blusa térmica masculina à segunda pele UV 50+, tecnologia para acompanhar você.</p></div><div className="product-grid">{products.map(item=><article className="product-card" key={item.name}><div className="product-image-wrap"><span className="product-badge">{item.badge}</span><button className="favorite" type="button" aria-label={`Favoritar ${item.name}`}><Icon name="heart" size={19}/></button><Image src={item.image} alt={item.name} fill sizes="(max-width: 639px) 80vw, (max-width: 1023px) 38vw, 23vw" className="product-image"/></div><div className="product-info"><p className={`availability ${item.tone}`}><span/>{item.availability}</p><div className="rating" aria-label="Avaliação ilustrativa: 5 de 5 estrelas"><span>★★★★★</span><small>(12)</small></div><h3>{item.name}</h3><p className="price">{item.price}</p><p className="installments">ou {item.installments} sem juros</p><Link href="/produto/camisa-termica" className="product-cta">Ver produto <Icon name="arrow" size={16}/></Link></div></article>)}</div><p className="demo-note">* Produtos, disponibilidade e valores demonstrativos.</p></div></section>
<section className="technology" id="tecnologia" aria-labelledby="technology-title"><div className="tech-grid-lines"/><div className="container-shell tech-content"><div className="tech-intro"><p className="eyebrow light"><span/>Tecnologia Info Trilhas</p><h2 id="technology-title">Proteção entre você e o ambiente.</h2><p>Desenvolvemos e fabricamos nossas próprias peças para transformar tecnologia, proteção e conforto em liberdade para seguir em frente.</p></div><div className="tech-list">{technology.map((item,index)=><article className="tech-item" key={item.title}><span className="tech-icon"><Icon name={item.icon} size={25}/></span><div><small>0{index+1}</small><h3>{item.title}</h3><p>{item.text}</p></div></article>)}</div></div></section>
<section className="section lines-section" id="linhas" aria-labelledby="lines-title"><div className="container-shell"><div className="center-heading"><p className="eyebrow"><span/>Três níveis de proteção</p><h2 id="lines-title">Uma linha para cada condição.</h2><p>Escolha pela finalidade: sol, frio intermediário ou baixas temperaturas.</p></div><div className="lines-grid">{lines.map(line=><article className="line-card" key={line.name}><div className="line-copy"><span className="line-kicker">{line.kicker}</span><h3>{line.name}</h3><p>{line.text}</p><small>{line.detail}</small><a href="#mais-vendidos" className="text-link light-link">Explorar linha <Icon name="arrow" size={17}/></a></div><Image src={line.image} alt={`Produto da linha ${line.name}`} fill sizes="(max-width: 767px) 90vw, 33vw"/></article>)}</div></div></section>
<section className="availability-section" aria-labelledby="availability-title"><div className="container-shell availability-inner"><div><p className="eyebrow light"><span/>Produção própria</p><h2 id="availability-title">Feito por nós.<br/>Preparado para você.</h2><p>Fabricamos nossos produtos e informamos com clareza o prazo de cada peça.</p></div><div className="availability-legend"><span className="ready"><i/>Pronta entrega<small>Disponível para envio</small></span><span className="demand"><i/>Produção sob demanda<small>Produzido após o pedido</small></span><span className="special"><i/>Encomenda especial<small>Consulte opções e prazo</small></span></div></div></section>
<section className="wholesale" id="atacado" aria-labelledby="wholesale-title"><div className="container-shell wholesale-inner"><div><p className="eyebrow light"><span/>Atacado e parceiros</p><h2 id="wholesale-title">Compre mais.<br/>Pague menos.</h2></div><div className="wholesale-copy"><p>Condições especiais para lojistas, grupos e compras em quantidade, direto de quem fabrica.</p><a href="#rodape" className="button button-gold">Conheça o atacado <Icon name="arrow" size={18}/></a></div></div></section>
<section className="benefits" aria-label="Benefícios Info Trilhas"><div className="container-shell benefits-grid">{benefits.map(item=><article key={item.title}><Icon name={item.icon} size={25}/><div><h3>{item.title}</h3><p>{item.text}</p></div></article>)}</div></section>
</main><Footer/></>}
