"use client";

import Image from "next/image";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { type MouseEvent, useRef } from "react";
import { Icon } from "./icons";
const navigation=["Motociclismo","Ciclismo","Corrida","Baixas temperaturas","Proteção UV","Atacado"];
const hrefFor=(item:string)=>item==="Atacado"?"#atacado":item==="Baixas temperaturas"?"#linhas":"#mais-vendidos";
export function Header(){const mobileMenuRef=useRef<HTMLDetailsElement>(null);const pathname=usePathname();const handleLogoClick=(event:MouseEvent<HTMLAnchorElement>,closeMenu=false)=>{if(closeMenu)mobileMenuRef.current?.removeAttribute("open");if(pathname==="/"){event.preventDefault();window.scrollTo({top:0,behavior:"smooth"})}};return <><div className="announcement"><p>Fabricação própria <span>•</span> Proteção para sol e frio <span>•</span> Enviamos para todo o Brasil</p></div><header className="site-header" id="top"><div className="header-main container-shell"><Link href="/" className="logo-link" aria-label="Info Trilhas — início" onClick={handleLogoClick}><Image src="/images/logo/logo-infotrilhas.png" alt="Info Trilhas" width={666} height={374} priority/></Link><nav className="desktop-nav" aria-label="Navegação principal">{navigation.map(item=><a href={hrefFor(item)} key={item}>{item}</a>)}</nav><div className="header-actions"><button type="button" aria-label="Buscar"><Icon name="search" size={21}/></button><button type="button" aria-label="Minha conta" className="desktop-action"><Icon name="user" size={21}/></button><button type="button" aria-label="Favoritos" className="desktop-action"><Icon name="heart" size={20}/></button><button type="button" aria-label="Carrinho" className="bag-button"><Icon name="bag" size={21}/><span>0</span></button><details ref={mobileMenuRef} className="mobile-menu"><summary aria-label="Abrir menu"><Icon name="menu" size={23}/></summary><div className="mobile-panel"><div className="mobile-panel-top"><span>Menu</span><button type="button" className="close-icon" aria-label="Fechar menu" onClick={()=>mobileMenuRef.current?.removeAttribute("open")}><Icon name="close" size={22}/></button></div><nav aria-label="Navegação mobile">{navigation.map(item=><a href={hrefFor(item)} key={item}>{item}<Icon name="arrow" size={17}/></a>)}<Link href="/admin" className="mobile-company-link">Área da Empresa<Icon name="arrow" size={17}/></Link></nav><div className="mobile-account"><a href="#rodape"><Icon name="user" size={20}/> Minha conta</a><a href="#rodape"><Icon name="heart" size={19}/> Favoritos</a></div><div className="mobile-menu-logo"><Link href="/" aria-label="Info Trilhas — início" onClick={event=>handleLogoClick(event,true)}><Image src="/images/logo/logo-infotrilhas.png" alt="Info Trilhas" width={666} height={374}/></Link></div></div></details></div></div></header></>}
